name       : libkipi
version    : 21.04.3
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/libkipi-21.04.3.tar.xz : c4065cd2d02cb2499abe62a677ff62bc49ecf05e250c23cfe664df8babee7f9d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
optimize   : lto
builddeps  :
    - kservice-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
