name       : libkipi
version    : 18.04.3
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/libkipi-18.04.3.tar.xz : f1c425d55427c04e734fa609cba116be3457a8faddec150ccbf6049dde4cd0d3
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
