name       : libkipi
version    : 16.12.3
release    : 2
source     :
    - http://download.kde.org/stable/applications/16.12.3/src/libkipi-16.12.3.tar.xz : e64f7f59c4ffc848a404d1a5d0df5b43ea223eaf81273b2ac72d84cac0063538
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
