name       : libkipi
version    : 19.08.2
release    : 29
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/libkipi-19.08.2.tar.xz : fcaf576afb961d9a36c1f69c034c43b9f0991cbd0726ea684c2c49096f36d5c6
license    : GPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
