name       : libkipi
version    : 20.04.2
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/libkipi-20.04.2.tar.xz : a1dabe2910b2a8cf74c6efa7b5164eea3bb9e9ab459939905e8c9fec7f991147
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
