name       : libkipi
version    : 20.12.3
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/libkipi-20.12.3.tar.xz : bb6fff214e3a74e17cb7b49f5e9a92252127ec6cb65e6832da3ac789c7bd14a8
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
optimize   : lto
builddeps  :
    - kservice-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
