name       : libkipi
version    : 21.08.2
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/libkipi-21.08.2.tar.xz : 90eb5f3b61b86b766d8c8da181b928d333d0df2dd34418553a3e11db9e52918c
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
optimize   : lto
builddeps  :
    - kservice-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
