name       : libkipi
version    : 18.08.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/libkipi-18.08.2.tar.xz : 0b0948082a3f41fa404e285656ada0eb3cd9a5bb3686f74fea3be944531b4b58
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
