name       : libkipi
version    : 17.08.1
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/libkipi-17.08.1.tar.xz : ab8b925164d6ead9c72068f1704e64784ff3b56982cc33822c7be7a466db2a21
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
