name       : libkipi
version    : 17.12.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/libkipi-17.12.3.tar.xz : f8d11c79dafcedca02996d1cf76790499fb941fd3dbf50b7ec99fd6dc3cb1b63
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
