name       : libkipi
version    : 18.12.2
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/libkipi-18.12.2.tar.xz : 49e7ccb3332438f38eb06140a529bafef1cb070c3e3dc6930553e24aaea6b2e9
license    : GPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
