name       : libkipi
version    : 21.08.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/libkipi-21.08.0.tar.xz : 06341e62c05068f8fda0ac63790bde315e9eed40d4d4a522fb6a04c2cde96120
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
optimize   : lto
builddeps  :
    - kservice-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
