name       : libkipi
version    : 21.04.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/libkipi-21.04.1.tar.xz : e736c0e665798a5948029a73434a834f70fe4073ac1cee8441127dead96af9cf
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
optimize   : lto
builddeps  :
    - kservice-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
