name       : libkipi
version    : 18.12.3
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/libkipi-18.12.3.tar.xz : 96abf4552d535cf101c76ff5b1cb0198eccfd4bdfb7dc192b66bf709af037a31
license    : GPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kservice-devel
    - kxmlgui-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
