name       : libkipi
version    : 21.12.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/libkipi-21.12.3.tar.xz : ec21153b3237c4f8a0bb9ce58498ae92d7e7d0362167772bace872d94ce45370
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : Interface to use kipi-plugins
description: |
    Libkipi is an interface to use kipi-plugins from a KDE image management program like digiKam.
optimize   : lto
builddeps  :
    - kservice-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
